apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: airpulse-k8s

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: airpulse
