apiVersion: v1
kind: Service
metadata:
  name: airpulse-service
  namespace: default
  labels:
    app.kubernetes.io/name: airpulse
    app.kubernetes.io/component: serving
spec:
  type: ClusterIP
  selector:
    app: airpulse-serving
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
